const express = require('express');
const router = express.Router();
const auth = require('../controllers/auth.controller');
const protect = require('../middleware/auth.middleware');
router.post('/register', auth.register);
router.post('/login', auth.login);
router.post('/forgot-password', auth.forgotPassword);
router.post('/reset-password', auth.resetPassword);
router.get('/me', protect, auth.me);
module.exports = router;
