const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/consent.controller');
const protect = require('../middleware/auth.middleware');
router.use(protect);
router.get('/', ctrl.listConsents);
router.post('/', ctrl.createConsent);
router.post('/approve', ctrl.approveConsent);
router.post('/reject', ctrl.rejectConsent);
router.post('/revoke', ctrl.revokeConsent);
module.exports = router;
