const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/user.controller');
const protect = require('../middleware/auth.middleware');
const adminOnly = require('../middleware/admin.middleware');
router.use(protect);
router.get('/profile', ctrl.getProfile);
router.put('/profile', ctrl.updateProfile);
router.put('/password', ctrl.updatePassword);
router.get('/all', adminOnly, ctrl.getAllUsers);
router.put('/:id/role', adminOnly, ctrl.updateUserRole);
module.exports = router;
