const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/user.controller');
const protect = require('../middleware/auth.middleware');
const adminOnly = require('../middleware/admin.middleware');
router.use(protect);
router.get('/profile', ctrl.getProfile);
router.get('/privacy-report', ctrl.downloadPrivacyReport);
router.put('/profile', ctrl.updateProfile);
router.put('/password', ctrl.updatePassword);
router.get('/all', adminOnly, ctrl.getAllUsers);
router.get('/:id/records', adminOnly, ctrl.getUserRecords);
router.put('/:id/role', adminOnly, ctrl.updateUserRole);
router.put('/:id/suspend', adminOnly, ctrl.suspendUser);
router.put('/:id/unsuspend', adminOnly, ctrl.unsuspendUser);
router.delete('/:id', adminOnly, ctrl.deleteUser);
module.exports = router;
